### ISSUE TITLE
Multi-linguale with translatable input/captions

### ISSUE THREAD

**Issue by sjorsschultz** [ahwelgemoed/app-guide-mendix-widget#2]
Is your feature request related to a problem? Please describe.
For a multi-language app users with different language settings all users see English button captions (skip/next/complet) and same step content

Describe the solution you'd like
Make configuration, content and button captions of widget translatable by adjusting language settings in Studio Pro.

Describe alternatives you've considered
Content is translatable with a workaround by passing $Language as contextparameter in string expression, but should be easier by just adjusting language in Studio Pro. Captions are not translatable at the moment.

**Comment by ahwelgemoed** [comment]
Hey - Sorry to hear about this. 
I don't work at or with Mendix anymore.  Please see this repo and create an issue [there](https://github.com/mendixlabs/app-services-components)
